USE endpointconfig;

INSERT INTO `manufacturer` (`name`, `description`) VALUES 
("Aastra", "Aastra"),
("Atcom", "IP Phone"),
("Atlinks", "Atlinks"),
("AudioCodes", "AudioCodes"),
("Cisco", "Cisco"),
("Damall", "Damall Technology Co"),
("Elastix", "PaloSanto Solution"),
("Escene", "Escene Communication"),
("Fanvil", "Fanvil Technology Co."),
("Grandstream", "Grandstream"),
("LG-ERICSSON", "LG-ERICSSON"),
("Linksys", "Linksys/Sipura"),
("Pingtel", "Generic"),
("Polycom", "Polycom"),
("Siemens", "Siemens"),
("Snom", "Snom360"),
("Thomson", "Generic"),
("Uniden", "Generic"),
("VOPTech", "VOPTech"),
("Xorcom", "Xorcom"),
("Yealink", "Yealink"),
("Zultys", "Zultys Technologies");

INSERT INTO `mac_prefix` (`mac_prefix`, `description`, `id_manufacturer`) VALUES
("00:08:5D", "Aastra", (SELECT `id` FROM manufacturer WHERE `name` = "Aastra")),
("00:09:45", "Atcom - Palmmicro Communication", (SELECT `id` FROM manufacturer WHERE `name` = "Atcom")),
("74:65:D1", "Atlinks", (SELECT `id` FROM manufacturer WHERE `name` = "Atlinks")),
("00:90:8F", "AudioCodes", (SELECT `id` FROM manufacturer WHERE `name` = "AudioCodes")),
("00:03:6B", "Cisco", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
("00:07:EB", "Cisco - 7940", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
("00:0B:5F", "Cisco - 7960", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
("00:0D:29", "Cisco 79xx", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
("00:0D:ED", "Cisco - 7960", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
("00:0E:38", "Cisco - 7960", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
("00:0F:23", "Cisco - 7960", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
("00:12:00", "Cisco - 7940", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
("00:12:43", "Cisco - 7940 ", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
("00:12:7F", "Cisco - 7690 ", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
("00:13:19", "Cisco - 7940", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
("00:13:C3", "Cisco - 7960", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
("00:14:A9", "Cisco - 7940", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
("00:15:FA", "Cisco - 7960", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
("00:16:46", "Cisco - 7940", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
("00:17:0E", "Cisco 79xx", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
("00:18:18", "Cisco - 7940", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
("00:18:73", "Cisco - 7940", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
("00:19:AA", "Cisco - 7940", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
("00:19:E7", "Cisco - 7940", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
("00:1A:6D", "Cisco - 7961 ", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
("00:1A:A1", "Cisco - 7961 ", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
("00:1B:53", "Cisco - 7931", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
("00:1E:4A", "Cisco  7906-7970 ", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
("00:21:55", "Cisco - 7961 ", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
("7C:14:76", "Damall", (SELECT `id` FROM manufacturer WHERE `name` = "Damall")),
("00:26:8B", "Escene", (SELECT `id` FROM manufacturer WHERE `name` = "Escene")),
("00:A8:59", "Fanvil", (SELECT `id` FROM manufacturer WHERE `name` = "Fanvil")),
("00:0B:82", "Grandstream", (SELECT `id` FROM manufacturer WHERE `name` = "Grandstream")),
("B4:0E:DC", "LG-ERICSSON", (SELECT `id` FROM manufacturer WHERE `name` = "LG-ERICSSON")),
("00:0E:08", "Linksys/Sipura", (SELECT `id` FROM manufacturer WHERE `name` = "Linksys")),
("00:D0:1E", "Pingtel - Generic", (SELECT `id` FROM manufacturer WHERE `name` = "Pingtel")),
("00:04:F2", "Polycom", (SELECT `id` FROM manufacturer WHERE `name` = "Polycom")),
("00:E0:DB", "Polycom - VSX7000A", (SELECT `id` FROM manufacturer WHERE `name` = "Polycom")),
("00:01:E3", "Siemens - SL75 WLAN", (SELECT `id` FROM manufacturer WHERE `name` = "Siemens")),
("00:04:13", "Snom360", (SELECT `id` FROM manufacturer WHERE `name` = "Snom")),
("00:04:23", "Snom360", (SELECT `id` FROM manufacturer WHERE `name` = "Snom")),
("00:04:25", "Snom300", (SELECT `id` FROM manufacturer WHERE `name` = "Snom")),
("00:04:27", "Snom320", (SELECT `id` FROM manufacturer WHERE `name` = "Snom")),
("00:0E:50", "Thomson - Generic", (SELECT `id` FROM manufacturer WHERE `name` = "Thomson")),
("00:14:7F", "Thomson - ST 2030", (SELECT `id` FROM manufacturer WHERE `name` = "Thomson")),
("00:18:F6", "Thomson - ST 2022 ", (SELECT `id` FROM manufacturer WHERE `name` = "Thomson")),
("00:E0:11", "Uniden - Generic", (SELECT `id` FROM manufacturer WHERE `name` = "Uniden")),
("00:0E:30", "VOPTech", (SELECT `id` FROM manufacturer WHERE `name` = "VOPTech")),
("64:24:00", "Xorcom", (SELECT `id` FROM manufacturer WHERE `name` = "Xorcom")),
("00:15:65", "Yealink", (SELECT `id` FROM manufacturer WHERE `name` = "Yealink")),
("00:0B:EA", "Zultys Technologies", (SELECT `id` FROM manufacturer WHERE `name` = "Zultys"));

INSERT INTO `model` (`max_accounts`, `static_ip_supported`, `dynamic_ip_supported`, `static_prov_supported`, `name`, `description`, `id_manufacturer`) VALUES
(9, 1, 1, 0, "480i", "480i", (SELECT `id` FROM manufacturer WHERE `name` = "Aastra")),
(9, 1, 1, 0, "480i CT", "480i CT", (SELECT `id` FROM manufacturer WHERE `name` = "Aastra")),
(1, 1, 1, 0, "51i", "51i", (SELECT `id` FROM manufacturer WHERE `name` = "Aastra")),
(9, 1, 1, 0, "53i", "53i", (SELECT `id` FROM manufacturer WHERE `name` = "Aastra")),
(9, 1, 1, 0, "55i", "55i", (SELECT `id` FROM manufacturer WHERE `name` = "Aastra")),
(9, 1, 1, 0, "57i", "57i", (SELECT `id` FROM manufacturer WHERE `name` = "Aastra")),
(9, 1, 1, 0, "57i CT", "53i CT", (SELECT `id` FROM manufacturer WHERE `name` = "Aastra")),
(6, 1, 1, 0, "6730i", "6730i", (SELECT `id` FROM manufacturer WHERE `name` = "Aastra")),
(6, 1, 1, 0, "6731i", "6731i", (SELECT `id` FROM manufacturer WHERE `name` = "Aastra")),
(9, 1, 1, 0, "6739i", "6739i", (SELECT `id` FROM manufacturer WHERE `name` = "Aastra")),
(9, 1, 1, 0, "6755i", "6755i", (SELECT `id` FROM manufacturer WHERE `name` = "Aastra")),
(9, 1, 1, 0, "6757i", "6757i", (SELECT `id` FROM manufacturer WHERE `name` = "Aastra")),
(1, 1, 1, 0, "9112i", "9112i", (SELECT `id` FROM manufacturer WHERE `name` = "Aastra")),
(9, 1, 1, 0, "9133i", "9133i", (SELECT `id` FROM manufacturer WHERE `name` = "Aastra")),
(9, 1, 1, 0, "9143i", "9143i", (SELECT `id` FROM manufacturer WHERE `name` = "Aastra")),
(9, 1, 1, 0, "9480i", "9480i", (SELECT `id` FROM manufacturer WHERE `name` = "Aastra")),
(9, 1, 1, 0, "9480i CT", "9480i CT", (SELECT `id` FROM manufacturer WHERE `name` = "Aastra")),
(1, 1, 1, 1, "AT320", "AT320", (SELECT `id` FROM manufacturer WHERE `name` = "Atcom")),
(3, 1, 1, 1, "AT530", "AT530", (SELECT `id` FROM manufacturer WHERE `name` = "Atcom")),
(2, 1, 1, 1, "AT610", "AT610", (SELECT `id` FROM manufacturer WHERE `name` = "Atcom")),
(3, 1, 1, 1, "AT620", "AT620", (SELECT `id` FROM manufacturer WHERE `name` = "Atcom")),
(5, 1, 1, 1, "AT640", "AT640", (SELECT `id` FROM manufacturer WHERE `name` = "Atcom")),
(1, 1, 1, 1, "AT800", "AT800", (SELECT `id` FROM manufacturer WHERE `name` = "Atcom")),
(6, 1, 1, 1, "Temporis IP800", "ALCATEL Temporis IP800", (SELECT `id` FROM manufacturer WHERE `name` = "Atlinks")),
(1, 1, 1, 1, "310HD", "310HD", (SELECT `id` FROM manufacturer WHERE `name` = "AudioCodes")),
(4, 1, 1, 1, "320HD", "320HD", (SELECT `id` FROM manufacturer WHERE `name` = "AudioCodes")),
(1, 0, 1, 0, "7690", "7690", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
(1, 0, 1, 0, "7906", "7906", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
(3, 0, 1, 0, "7931", "7931", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
(2, 0, 1, 0, "7940", "7940", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
(6, 0, 1, 0, "7960", "7960", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
(6, 0, 1, 0, "7961", "7961", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
(8, 0, 1, 0, "7970", "7970", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
(8, 0, 1, 0, "7971", "7971", (SELECT `id` FROM manufacturer WHERE `name` = "Cisco")),
(2, 1, 1, 1, "D-3310", "D-3310", (SELECT `id` FROM manufacturer WHERE `name` = "Damall")),
(2, 1, 1, 1, "LXP100", "LXP100", (SELECT `id` FROM manufacturer WHERE `name` = "Elastix")),
(2, 1, 1, 1, "LXP200", "LXP200", (SELECT `id` FROM manufacturer WHERE `name` = "Elastix")),
(8, 1, 1, 1, "ES620", "ES620", (SELECT `id` FROM manufacturer WHERE `name` = "Escene")),
(2, 1, 1, 1, "C56", "C56/C56P", (SELECT `id` FROM manufacturer WHERE `name` = "Fanvil")),
(3, 1, 1, 1, "C58", "C58/C58P", (SELECT `id` FROM manufacturer WHERE `name` = "Fanvil")),
(4, 1, 1, 1, "C60", "C60", (SELECT `id` FROM manufacturer WHERE `name` = "Fanvil")),
(5, 1, 1, 1, "C62", "C62", (SELECT `id` FROM manufacturer WHERE `name` = "Fanvil")),
(1, 1, 1, 1, "BT200", "BT200", (SELECT `id` FROM manufacturer WHERE `name` = "Grandstream")),
(2, 1, 1, 0, "HT386", "HT386", (SELECT `id` FROM manufacturer WHERE `name` = "Grandstream")),
(1, 1, 1, 1, "GXP280", "GXP280", (SELECT `id` FROM manufacturer WHERE `name` = "Grandstream")),
(2, 1, 1, 1, "GXP1400", "GXP1400", (SELECT `id` FROM manufacturer WHERE `name` = "Grandstream")),
(2, 1, 1, 1, "GXP1405", "GXP1405", (SELECT `id` FROM manufacturer WHERE `name` = "Grandstream")),
(2, 1, 1, 1, "GXP1450", "GXP1450", (SELECT `id` FROM manufacturer WHERE `name` = "Grandstream")),
(4, 1, 1, 0, "GXP2000", "GXP2000", (SELECT `id` FROM manufacturer WHERE `name` = "Grandstream")),
(6, 1, 1, 0, "GXP2020", "GXP2020", (SELECT `id` FROM manufacturer WHERE `name` = "Grandstream")),
(4, 1, 1, 0, "GXP2100", "GXP2100", (SELECT `id` FROM manufacturer WHERE `name` = "Grandstream")),
(6, 1, 1, 0, "GXP2120", "GXP2120", (SELECT `id` FROM manufacturer WHERE `name` = "Grandstream")),
(6, 1, 1, 0, "GXP2200", "GXP2200", (SELECT `id` FROM manufacturer WHERE `name` = "Grandstream")),
(3, 1, 1, 0, "GXV3140", "GXV3140", (SELECT `id` FROM manufacturer WHERE `name` = "Grandstream")),
(3, 1, 1, 0, "GXV3175", "GXV3175", (SELECT `id` FROM manufacturer WHERE `name` = "Grandstream")),
(1, 1, 1, 0, "IP8802", "IP8802/8802A", (SELECT `id` FROM manufacturer WHERE `name` = "LG-ERICSSON")),
(2, 1, 1, 0, "SPA841", "SPA841", (SELECT `id` FROM manufacturer WHERE `name` = "Linksys")),
(1, 1, 1, 0, "SPA921", "SPA921", (SELECT `id` FROM manufacturer WHERE `name` = "Linksys")),
(1, 1, 1, 0, "SPA922", "SPA922", (SELECT `id` FROM manufacturer WHERE `name` = "Linksys")),
(2, 1, 1, 0, "SPA941", "SPA941", (SELECT `id` FROM manufacturer WHERE `name` = "Linksys")),
(4, 1, 1, 0, "SPA942", "SPA942", (SELECT `id` FROM manufacturer WHERE `name` = "Linksys")),
(6, 1, 1, 0, "SPA962", "SPA962", (SELECT `id` FROM manufacturer WHERE `name` = "Linksys")),
(2, 0, 1, 0, "IP 301", "IP 301", (SELECT `id` FROM manufacturer WHERE `name` = "Polycom")),
(2, 0, 1, 0, "IP 330/320", "IP 330/320", (SELECT `id` FROM manufacturer WHERE `name` = "Polycom")),
(2, 0, 1, 0, "IP 430", "IP 430", (SELECT `id` FROM manufacturer WHERE `name` = "Polycom")),
(3, 0, 1, 0, "IP 501", "IP 501", (SELECT `id` FROM manufacturer WHERE `name` = "Polycom")),
(4, 0, 1, 0, "IP 550", "IP 550", (SELECT `id` FROM manufacturer WHERE `name` = "Polycom")),
(6, 0, 1, 0, "IP 601", "IP 601", (SELECT `id` FROM manufacturer WHERE `name` = "Polycom")),
(34, 0, 1, 0, "IP 650", "IP 650", (SELECT `id` FROM manufacturer WHERE `name` = "Polycom")),
(1, 1, 1, 0, "SoundStation IP 4000", "SoundStation IP 4000", (SELECT `id` FROM manufacturer WHERE `name` = "Polycom")),
(1, 1, 1, 0, "VSX7000A", "VSX7000A", (SELECT `id` FROM manufacturer WHERE `name` = "Polycom")),
(1, 1, 1, 0, "SL75 WLAN", "SL75 WLAN", (SELECT `id` FROM manufacturer WHERE `name` = "Siemens")),
(4, 1, 1, 1, "300", "300", (SELECT `id` FROM manufacturer WHERE `name` = "Snom")),
(12, 1, 1, 1, "320", "320", (SELECT `id` FROM manufacturer WHERE `name` = "Snom")),
(12, 1, 1, 1, "360", "360", (SELECT `id` FROM manufacturer WHERE `name` = "Snom")),
(12, 1, 1, 1, "821", "snom821-SIP", (SELECT `id` FROM manufacturer WHERE `name` = "Snom")),
(9, 1, 1, 1, "m9", "m9", (SELECT `id` FROM manufacturer WHERE `name` = "Snom")),
(2, 1, 1, 0, "ST 2022", "ST 2022", (SELECT `id` FROM manufacturer WHERE `name` = "Thomson")),
(1, 1, 1, 0, "ST 2030", "ST 2030", (SELECT `id` FROM manufacturer WHERE `name` = "Thomson")),
(2, 1, 1, 1, "VI2006", "VI2006", (SELECT `id` FROM manufacturer WHERE `name` = "VOPTech")),
(3, 1, 1, 1, "VI2007", "VI2007", (SELECT `id` FROM manufacturer WHERE `name` = "VOPTech")),
(4, 1, 1, 1, "VI2008", "VI2008", (SELECT `id` FROM manufacturer WHERE `name` = "VOPTech")),
(2, 1, 1, 0, "XP0100P", "XP0100P", (SELECT `id` FROM manufacturer WHERE `name` = "Xorcom")),
(3, 1, 1, 0, "XP0120P", "XP0120P", (SELECT `id` FROM manufacturer WHERE `name` = "Xorcom")),
(2, 1, 1, 1, "SIP-T20/T20P", "SIP-T20/T20P", (SELECT `id` FROM manufacturer WHERE `name` = "Yealink")),
(3, 1, 1, 1, "SIP-T22/T22P", "SIP-T22/T22P", (SELECT `id` FROM manufacturer WHERE `name` = "Yealink")),
(3, 1, 1, 1, "SIP-T26/T26P", "SIP-T26/T26P", (SELECT `id` FROM manufacturer WHERE `name` = "Yealink")),
(6, 1, 1, 1, "SIP-T28/T28P", "SIP-T28/T28P", (SELECT `id` FROM manufacturer WHERE `name` = "Yealink")),
(6, 1, 1, 1, "SIP-T38G", "SIP-T38G", (SELECT `id` FROM manufacturer WHERE `name` = "Yealink")),
(4, 1, 1, 1, "VP530", "VP530", (SELECT `id` FROM manufacturer WHERE `name` = "Yealink")),
(1, 0, 1, 0, "ZIP2x1", "Zultys ZIP 2x1", (SELECT `id` FROM manufacturer WHERE `name` = "Zultys")),
(1, 0, 1, 0, "ZIP2x2", "Zultys ZIP 2x2", (SELECT `id` FROM manufacturer WHERE `name` = "Zultys"));

INSERT INTO `model_properties` (`property_key`, `property_value`, `id_model`) VALUES
("max_sip_accounts", "9", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "480i")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "480i")),
("max_sip_accounts", "9", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "480i CT")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "480i CT")),
("max_sip_accounts", "1", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "51i")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "51i")),
("max_sip_accounts", "9", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "53i")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "53i")),
("max_sip_accounts", "9", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "55i")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "55i")),
("max_sip_accounts", "9", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "57i")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "57i")),
("max_sip_accounts", "9", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "57i CT")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "57i CT")),
("max_sip_accounts", "6", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "6730i")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "6730i")),
("max_sip_accounts", "6", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "6731i")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "6731i")),
("max_sip_accounts", "9", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "6739i")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "6739i")),
("max_sip_accounts", "9", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "6755i")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "6755i")),
("max_sip_accounts", "9", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "6757i")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "6757i")),
("max_sip_accounts", "1", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "9112i")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "9112i")),
("max_sip_accounts", "9", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "9133i")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "9133i")),
("max_sip_accounts", "9", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "9143i")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "9143i")),
("max_sip_accounts", "9", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "9480i")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "9480i")),
("max_sip_accounts", "9", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "9480i CT")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "9480i CT")),
("max_sip_accounts", "1", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT320")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT320")),
("max_sip_accounts", "2", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT530")),
("max_iax2_accounts", "1", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT530")),
("max_sip_accounts", "2", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT610")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT610")),
("max_sip_accounts", "2", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT620")),
("max_iax2_accounts", "1", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT620")),
("max_sip_accounts", "4", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT640")),
("max_iax2_accounts", "1", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT640")),
("max_sip_accounts", "1", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT800")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT800")),
("max_sip_accounts", "6", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atlinks" AND model.name = "Temporis IP800")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atlinks" AND model.name = "Temporis IP800")),
("max_sip_accounts", "1", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "AudioCodes" AND model.name = "310HD")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "AudioCodes" AND model.name = "310HD")),
("max_sip_accounts", "4", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "AudioCodes" AND model.name = "320HD")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "AudioCodes" AND model.name = "320HD")),
("max_sip_accounts", "1", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Cisco" AND model.name = "7690")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Cisco" AND model.name = "7690")),
("max_sip_accounts", "1", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Cisco" AND model.name = "7906")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Cisco" AND model.name = "7906")),
("max_sip_accounts", "3", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Cisco" AND model.name = "7931")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Cisco" AND model.name = "7931")),
("max_sip_accounts", "2", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Cisco" AND model.name = "7940")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Cisco" AND model.name = "7940")),
("max_sip_accounts", "6", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Cisco" AND model.name = "7960")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Cisco" AND model.name = "7960")),
("max_sip_accounts", "6", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Cisco" AND model.name = "7961")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Cisco" AND model.name = "7961")),
("max_sip_accounts", "8", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Cisco" AND model.name = "7970")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Cisco" AND model.name = "7970")),
("max_sip_accounts", "8", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Cisco" AND model.name = "7971")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Cisco" AND model.name = "7971")),
("max_sip_accounts", "2", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Damall" AND model.name = "D-3310")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Damall" AND model.name = "D-3310")),
("max_sip_accounts", "2", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Elastix" AND model.name = "LXP100")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Elastix" AND model.name = "LXP100")),
("max_sip_accounts", "2", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Elastix" AND model.name = "LXP200")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Elastix" AND model.name = "LXP200")),
("max_sip_accounts", "8", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Escene" AND model.name = "ES620")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Escene" AND model.name = "ES620")),
("max_sip_accounts", "2", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Fanvil" AND model.name = "C56")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Fanvil" AND model.name = "C56")),
("max_sip_accounts", "2", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Fanvil" AND model.name = "C58")),
("max_iax2_accounts", "1", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Fanvil" AND model.name = "C58")),
("max_sip_accounts", "3", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Fanvil" AND model.name = "C60")),
("max_iax2_accounts", "1", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Fanvil" AND model.name = "C60")),
("max_sip_accounts", "4", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Fanvil" AND model.name = "C62")),
("max_iax2_accounts", "1", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Fanvil" AND model.name = "C62")),
("max_sip_accounts", "1", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "BT200")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "BT200")),
("max_sip_accounts", "2", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "HT386")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "HT386")),
("max_sip_accounts", "1", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP280")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP280")),
("max_sip_accounts", "2", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP1400")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP1400")),
("max_sip_accounts", "2", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP1405")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP1405")),
("max_sip_accounts", "2", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP1450")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP1450")),
("max_sip_accounts", "4", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP2000")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP2000")),
("max_sip_accounts", "6", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP2020")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP2020")),
("max_sip_accounts", "4", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP2100")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP2100")),
("max_sip_accounts", "6", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP2120")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP2120")),
("max_sip_accounts", "6", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP2200")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP2200")),
("max_sip_accounts", "3", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXV3140")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXV3140")),
("max_sip_accounts", "3", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXV3175")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXV3175")),
("max_sip_accounts", "1", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "LG-ERICSSON" AND model.name = "IP8802")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "LG-ERICSSON" AND model.name = "IP8802")),
("max_sip_accounts", "2", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Linksys" AND model.name = "SPA841")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Linksys" AND model.name = "SPA841")),
("max_sip_accounts", "1", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Linksys" AND model.name = "SPA921")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Linksys" AND model.name = "SPA921")),
("max_sip_accounts", "1", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Linksys" AND model.name = "SPA922")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Linksys" AND model.name = "SPA922")),
("max_sip_accounts", "2", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Linksys" AND model.name = "SPA941")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Linksys" AND model.name = "SPA941")),
("max_sip_accounts", "4", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Linksys" AND model.name = "SPA942")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Linksys" AND model.name = "SPA942")),
("max_sip_accounts", "6", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Linksys" AND model.name = "SPA962")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Linksys" AND model.name = "SPA962")),
("max_sip_accounts", "2", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Polycom" AND model.name = "IP 301")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Polycom" AND model.name = "IP 301")),
("max_sip_accounts", "2", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Polycom" AND model.name = "IP 330/320")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Polycom" AND model.name = "IP 330/320")),
("max_sip_accounts", "2", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Polycom" AND model.name = "IP 430")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Polycom" AND model.name = "IP 430")),
("max_sip_accounts", "3", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Polycom" AND model.name = "IP 501")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Polycom" AND model.name = "IP 501")),
("max_sip_accounts", "4", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Polycom" AND model.name = "IP 550")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Polycom" AND model.name = "IP 550")),
("max_sip_accounts", "6", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Polycom" AND model.name = "IP 601")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Polycom" AND model.name = "IP 601")),
("max_sip_accounts", "34", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Polycom" AND model.name = "IP 650")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Polycom" AND model.name = "IP 650")),
("max_sip_accounts", "1", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Polycom" AND model.name = "SoundStation IP 4000")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Polycom" AND model.name = "SoundStation IP 4000")),
("max_sip_accounts", "1", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Polycom" AND model.name = "VSX7000A")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Polycom" AND model.name = "VSX7000A")),
("max_sip_accounts", "1", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Siemens" AND model.name = "SL75 WLAN")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Siemens" AND model.name = "SL75 WLAN")),
("max_sip_accounts", "4", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Snom" AND model.name = "300")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Snom" AND model.name = "300")),
("max_sip_accounts", "12", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Snom" AND model.name = "320")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Snom" AND model.name = "320")),
("max_sip_accounts", "12", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Snom" AND model.name = "360")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Snom" AND model.name = "360")),
("max_sip_accounts", "12", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Snom" AND model.name = "821")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Snom" AND model.name = "821")),
("max_sip_accounts", "9", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Snom" AND model.name = "m9")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Snom" AND model.name = "m9")),
("max_sip_accounts", "2", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Thomson" AND model.name = "ST 2022")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Thomson" AND model.name = "ST 2022")),
("max_sip_accounts", "2", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Thomson" AND model.name = "ST 2030")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Thomson" AND model.name = "ST 2030")),
("max_sip_accounts", "2", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "VOPTech" AND model.name = "VI2006")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "VOPTech" AND model.name = "VI2006")),
("max_sip_accounts", "2", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "VOPTech" AND model.name = "VI2007")),
("max_iax2_accounts", "1", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "VOPTech" AND model.name = "VI2007")),
("max_sip_accounts", "3", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "VOPTech" AND model.name = "VI2008")),
("max_iax2_accounts", "1", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "VOPTech" AND model.name = "VI2008")),
("max_sip_accounts", "2", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Xorcom" AND model.name = "XP0100P")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Xorcom" AND model.name = "XP0100P")),
("max_sip_accounts", "3", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Xorcom" AND model.name = "XP0120P")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Xorcom" AND model.name = "XP0120P")),
("max_sip_accounts", "2", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Yealink" AND model.name = "SIP-T20/T20P")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Yealink" AND model.name = "SIP-T20/T20P")),
("max_sip_accounts", "3", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Yealink" AND model.name = "SIP-T22/T22P")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Yealink" AND model.name = "SIP-T22/T22P")),
("max_sip_accounts", "3", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Yealink" AND model.name = "SIP-T26/T26P")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Yealink" AND model.name = "SIP-T26/T26P")),
("max_sip_accounts", "6", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Yealink" AND model.name = "SIP-T28/T28P")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Yealink" AND model.name = "SIP-T28/T28P")),
("max_sip_accounts", "4", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Yealink" AND model.name = "VP530")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Yealink" AND model.name = "VP530")),
("max_sip_accounts", "6", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Yealink" AND model.name = "SIP-T38G")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Yealink" AND model.name = "SIP-T38G")),
("max_sip_accounts", "1", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Zultys" AND model.name = "ZIP2x1")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Zultys" AND model.name = "ZIP2x1")),
("max_sip_accounts", "1", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Zultys" AND model.name = "ZIP2x2")),
("max_iax2_accounts", "0", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Zultys" AND model.name = "ZIP2x2"));

INSERT INTO `model_properties` (`property_key`, `property_value`, `id_model`) VALUES
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "480i")),
("http_password", "22222", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "480i")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "480i CT")),
("http_password", "22222", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "480i CT")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "51i")),
("http_password", "22222", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "51i")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "53i")),
("http_password", "22222", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "53i")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "55i")),
("http_password", "22222", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "55i")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "57i")),
("http_password", "22222", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "57i")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "57i CT")),
("http_password", "22222", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "57i CT")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "6730i")),
("http_password", "22222", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "6730i")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "6731i")),
("http_password", "22222", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "6731i")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "6739i")),
("http_password", "22222", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "6739i")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "6755i")),
("http_password", "22222", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "6755i")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "6757i")),
("http_password", "22222", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "6757i")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "9112i")),
("http_password", "22222", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "9112i")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "9133i")),
("http_password", "22222", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "9133i")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "9143i")),
("http_password", "22222", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "9143i")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "9480i")),
("http_password", "22222", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "9480i")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "9480i CT")),
("http_password", "22222", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Aastra" AND model.name = "9480i CT")),
("telnet_password", "12345678", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT320")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT320")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT320")),
("telnet_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT530")),
("telnet_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT530")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT530")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT530")),
("telnet_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT610")),
("telnet_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT610")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT610")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT610")),
("telnet_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT620")),
("telnet_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT620")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT620")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT620")),
("telnet_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT640")),
("telnet_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT640")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT640")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atcom" AND model.name = "AT640")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atlinks" AND model.name = "Temporis IP800")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Atlinks" AND model.name = "Temporis IP800")),
("telnet_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "AudioCodes" AND model.name = "310HD")),
("telnet_password", "1234", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "AudioCodes" AND model.name = "310HD")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "AudioCodes" AND model.name = "310HD")),
("http_password", "1234", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "AudioCodes" AND model.name = "310HD")),
("telnet_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "AudioCodes" AND model.name = "320HD")),
("telnet_password", "1234", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "AudioCodes" AND model.name = "320HD")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "AudioCodes" AND model.name = "320HD")),
("http_password", "1234", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "AudioCodes" AND model.name = "320HD")),
("telnet_password", "cisco", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Cisco" AND model.name = "7690")),
("telnet_password", "cisco", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Cisco" AND model.name = "7906")),
("telnet_password", "cisco", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Cisco" AND model.name = "7931")),
("telnet_password", "cisco", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Cisco" AND model.name = "7940")),
("telnet_password", "cisco", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Cisco" AND model.name = "7960")),
("telnet_password", "cisco", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Cisco" AND model.name = "7961")),
("telnet_password", "cisco", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Cisco" AND model.name = "7970")),
("telnet_password", "cisco", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Cisco" AND model.name = "7971")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Damall" AND model.name = "D-3310")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Damall" AND model.name = "D-3310")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Elastix" AND model.name = "LXP100")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Elastix" AND model.name = "LXP200")),
("telnet_username", "root", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Escene" AND model.name = "ES620")),
("telnet_password", "root", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Escene" AND model.name = "ES620")),
("http_username", "root", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Escene" AND model.name = "ES620")),
("http_password", "root", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Escene" AND model.name = "ES620")),
("telnet_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Fanvil" AND model.name = "C56")),
("telnet_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Fanvil" AND model.name = "C56")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Fanvil" AND model.name = "C56")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Fanvil" AND model.name = "C56")),
("telnet_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Fanvil" AND model.name = "C58")),
("telnet_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Fanvil" AND model.name = "C58")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Fanvil" AND model.name = "C58")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Fanvil" AND model.name = "C58")),
("telnet_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Fanvil" AND model.name = "C60")),
("telnet_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Fanvil" AND model.name = "C60")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Fanvil" AND model.name = "C60")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Fanvil" AND model.name = "C60")),
("telnet_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Fanvil" AND model.name = "C62")),
("telnet_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Fanvil" AND model.name = "C62")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Fanvil" AND model.name = "C62")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Fanvil" AND model.name = "C62")),
("telnet_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "BT200")),
("telnet_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "HT386")),
("telnet_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP280")),
("telnet_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP1400")),
("telnet_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP1405")),
("ssh_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP1450")),
("ssh_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP1450")),
("telnet_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP2000")),
("telnet_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP2020")),
("telnet_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP2100")),
("telnet_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP2120")),
("ssh_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP2200")),
("ssh_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP2200")),
("telnet_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXV3140")),
("telnet_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXV3175")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "BT200")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "HT386")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP280")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP1400")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP1405")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP1450")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP1450")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP2000")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP2020")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP2100")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP2120")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP2200")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXP2200")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXV3140")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXV3175")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXV3140")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Grandstream" AND model.name = "GXV3175")),
("telnet_username", "private", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "LG-ERICSSON" AND model.name = "IP8802")),
("telnet_password", "lip", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "LG-ERICSSON" AND model.name = "IP8802")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Snom" AND model.name = "m9")),
("http_password", "password", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Snom" AND model.name = "m9")),
("telnet_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "VOPTech" AND model.name = "VI2006")),
("telnet_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "VOPTech" AND model.name = "VI2006")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "VOPTech" AND model.name = "VI2006")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "VOPTech" AND model.name = "VI2006")),
("telnet_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "VOPTech" AND model.name = "VI2007")),
("telnet_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "VOPTech" AND model.name = "VI2007")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "VOPTech" AND model.name = "VI2007")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "VOPTech" AND model.name = "VI2007")),
("telnet_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "VOPTech" AND model.name = "VI2008")),
("telnet_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "VOPTech" AND model.name = "VI2008")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "VOPTech" AND model.name = "VI2008")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "VOPTech" AND model.name = "VI2008")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Yealink" AND model.name = "SIP-T20/T20P")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Yealink" AND model.name = "SIP-T20/T20P")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Yealink" AND model.name = "SIP-T22/T22P")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Yealink" AND model.name = "SIP-T22/T22P")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Yealink" AND model.name = "SIP-T26/T26P")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Yealink" AND model.name = "SIP-T26/T26P")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Yealink" AND model.name = "SIP-T28/T28P")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Yealink" AND model.name = "SIP-T28/T28P")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Yealink" AND model.name = "SIP-T38G")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Yealink" AND model.name = "SIP-T38G")),
("http_username", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Yealink" AND model.name = "VP530")),
("http_password", "admin", (SELECT model.id FROM manufacturer, model WHERE manufacturer.id = model.id_manufacturer AND manufacturer.name = "Yealink" AND model.name = "VP530"));

