[HW_CONFIG]
lcd_contrast=8
ring_volume=5
speaker_volume=5
handset_volume=5

[NET_CONFIG]
use_dhcp=yes
;ip_addr=
;subnet_mask=
;default_gateway=
;primary_dns=
;secondary_dns=
domain=zultys.com
sntp_server_addr={$SERVER_IP}
tftp_server_addr={$SERVER_IP}
tftp_cfg_dir=./{$MODEL}
;dscp_setting=0

[SIP_CONFIG]
phone_sip_port=5060
rtp_start_port=33000
register_w_proxy=yes
proxy_addr={$SERVER_IP}
proxy_port=5060
voice_mail_uri=*98
registration_expires=3600
session_expires=3600

[AUDIO_INFO]
ext_ring_tone=0
ext_cust_ring=
int_ring_tone=0
int_cust_ring=
ring_tone2=0
cust_ring2=
key_click=0
codec=0
distinctive_ring=yes
sound_url=
ext_call_answer=0

[GENERAL_INFO]
software_version=1.0.0
password=123456
time_fmt=%H:%M
date_fmt=%m/%-d/%Y
date_time_order=0
timezone=-420
country=USA
language=es_ES.iso88591
clear_settings=2

[VLAN_CONFIG]
mode=0
vlan_id_a=10
circuits_a=UET
vlan_id_b=30
circuits_b=EUT
cos_setting=5